% generateFig_SamplePressureCurves_Revision
clear all
close all
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Lucy\Dropbox (MIT)\rochegroup\Lucy\MATLAB in vivo Data Processing\data\inVitro_Diego_Data.xlsx
%    Worksheet: Tensile Force
%
% Auto-generated by MATLAB on 08-May-2022 12:55:55

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Tensile Force";
opts.DataRange = "A5:M95";

% Specify column names and types
opts.VariableNames = ["Times", "Curve5Pressurepsi", "ForceN", "Curve10Pressurepsi1", "ForceN1", "Curve15Pressurepsi2", "ForceN2", "Curve20Pressurepsi3", "ForceN3", "TriPressurepsi4", "ForceN4", "SqPressurepsi5", "ForceN5"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
inVitroTensile_PF_Data = readtable("inVitro_Diego_Data.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%%

Color5 = hex2rgb('#C9DEDB');
Color10 = hex2rgb('#83ABA4');
Color15 = hex2rgb('#428C80');
Color20 = hex2rgb('#146759');
ColorTri = hex2rgb('#DDCC77');
ColorSq = hex2rgb('#CC6677');
% ColorSpont = [0.3 0.3 0.3];

f1=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.Curve5Pressurepsi,'Color',Color5,'LineWidth',1.5)
plottype1 = 'Curve5_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

f2=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.Curve10Pressurepsi1,'Color',Color10,'LineWidth',1.5)
plottype2 = 'Curve10_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

f3=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.Curve15Pressurepsi2,'Color',Color15,'LineWidth',1.5)
plottype3 = 'Curve15_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

f4=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.Curve20Pressurepsi3,'Color',Color20,'LineWidth',1.5)
plottype4 = 'Curve20_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

f5=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.TriPressurepsi4,'Color',ColorTri,'LineWidth',1.5)
plottype5 = 'Tri20_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

%Sq wave requires processing
TF = islocalmin(inVitroTensile_PF_Data.SqPressurepsi5,'MinSeparation',20);
ind = find(TF);
SqPress = inVitroTensile_PF_Data.SqPressurepsi5;
SqPress(1:ind(1)-1)=zeros(size(SqPress(1:ind(1)-1)));
SqPress(ind(2)+1:end)=zeros(size(SqPress(ind(2)+1:end)));
% figure
% plot(inVitroTensile_PF_Data.Times,inVitroTensile_PF_Data.SqPressurepsi5,inVitroTensile_PF_Data.Times(TF),inVitroTensile_PF_Data.SqPressurepsi5(TF),'ok')
% hold on
% plot(inVitroTensile_PF_Data.Times,SqPress)
% hold off
f6=figure('Position',[100 100 250 150]);
plot(inVitroTensile_PF_Data.Times,SqPress,'Color',ColorSq,'LineWidth',1.5)
plottype6 = 'Sq20_P';
xlabel('Time [s]')
xlim([0 1.818])
ylabel('Actuator Pressure [psi]')
ylim([0 23])
yticks([0 5 10 15 20])

%% Save
pathWithFolderName =  strcat(pwd,'\Figures For Paper\');
Condition = 'SampleCurve';

figName1 = strcat(plottype1,Condition);
figFileName1 = strcat(pathWithFolderName,figName1);
exportgraphics(f1,strcat(figFileName1,'.eps'),'ContentType','vector') %will save figure f
figName2 = strcat(plottype2,Condition);
figFileName2 = strcat(pathWithFolderName,figName2);
exportgraphics(f2,strcat(figFileName2,'.eps'),'ContentType','vector') %will save figure f
figName3 = strcat(plottype3,Condition);
figFileName3 = strcat(pathWithFolderName,figName3);
exportgraphics(f3,strcat(figFileName3,'.eps'),'ContentType','vector') %will save figure f
figName4 = strcat(plottype4,Condition);
figFileName4 = strcat(pathWithFolderName,figName4);
exportgraphics(f4,strcat(figFileName4,'.eps'),'ContentType','vector') %will save figure f 
figName5 = strcat(plottype5,Condition);
figFileName5 = strcat(pathWithFolderName,figName5);
exportgraphics(f5,strcat(figFileName5,'.eps'),'ContentType','vector') %will save figure f 
figName6 = strcat(plottype6,Condition);
figFileName6 = strcat(pathWithFolderName,figName6);
exportgraphics(f6,strcat(figFileName6,'.eps'),'ContentType','vector') %will save figure f 
