%generateFig_MaxTensForce_Revision
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Lucy\Dropbox (MIT)\rochegroup\Lucy\MATLAB in vivo Data Processing\data\inVitro_Diego_Data.xlsx
%    Worksheet: MATLABTens
%
% Auto-generated by MATLAB on 08-May-2022 16:45:16

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "MATLABTens";
opts.DataRange = "A1:B40";

% Specify column names and types
opts.VariableNames = ["P", "F"];
opts.VariableTypes = ["double", "double"];

% Import the data
MaxTens = readtable("inVitro_Diego_Data.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%%

f1=figure('Position',[100 100 250 250]);
plot(MaxTens.P,MaxTens.F,'.','Color',[0.4 0.4 0.4])
plottype1 = 'TensxPSI';
xlabel('Peak Actuator Pressure [psi]')
xlim([0 25])
xticks([0 5 10 15 20])
ylabel('Peak Tensile Force [N]')
ylim([0 45])


%% Save
pathWithFolderName =  strcat(pwd,'\Figures For Paper\');
Condition = 'SampleTensileCurve';

figName1 = strcat(plottype1,Condition);
figFileName1 = strcat(pathWithFolderName,figName1);
exportgraphics(f1,strcat(figFileName1,'.eps'),'ContentType','vector') %will save figure f
